// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhWLN-otcLgoSRSkZ0YmcPEfqTTCiuHDY',
    appId: '1:613443004676:web:b7ec681b0bfdba90ff0851',
    messagingSenderId: '613443004676',
    projectId: 'muslim-app-54d36',
    authDomain: 'muslim-app-54d36.firebaseapp.com',
    storageBucket: 'muslim-app-54d36.firebasestorage.app',
    measurementId: 'G-F9H0Q8F3TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYYebv-GVz-9_uYtUXQB69NT4LuIuE0hU',
    appId: '1:613443004676:android:c13bb79646a04002ff0851',
    messagingSenderId: '613443004676',
    projectId: 'muslim-app-54d36',
    storageBucket: 'muslim-app-54d36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGy0vaC2Ux4S8JC4nF2H7TLo88Sap56eU',
    appId: '1:613443004676:ios:5e18fe61de1b687cff0851',
    messagingSenderId: '613443004676',
    projectId: 'muslim-app-54d36',
    storageBucket: 'muslim-app-54d36.firebasestorage.app',
    iosBundleId: 'com.example.muslimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGy0vaC2Ux4S8JC4nF2H7TLo88Sap56eU',
    appId: '1:613443004676:ios:5e18fe61de1b687cff0851',
    messagingSenderId: '613443004676',
    projectId: 'muslim-app-54d36',
    storageBucket: 'muslim-app-54d36.firebasestorage.app',
    iosBundleId: 'com.example.muslimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhWLN-otcLgoSRSkZ0YmcPEfqTTCiuHDY',
    appId: '1:613443004676:web:babadeec0f81773aff0851',
    messagingSenderId: '613443004676',
    projectId: 'muslim-app-54d36',
    authDomain: 'muslim-app-54d36.firebaseapp.com',
    storageBucket: 'muslim-app-54d36.firebasestorage.app',
    measurementId: 'G-RW779KFB4L',
  );
}
